const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('electronAPI', {
  showOpenDialog: () => ipcRenderer.invoke('show-open-dialog'),
  readExcel: (filePath) => ipcRenderer.invoke('read-excel', filePath),
  startCheck: (data, config, filePath) => ipcRenderer.invoke('start-check', { data, config, filePath }),
  getCurrentRow: () => ipcRenderer.invoke('get-current-row'),
  nextRow: () => ipcRenderer.invoke('next-row'),
  copyToClipboard: (text) => ipcRenderer.invoke('copy-to-clipboard', text),
  openNoteWindow: (rowData, rowIndex) => ipcRenderer.invoke('open-note-window', { rowData, rowIndex }),
  getPendingMarkData: () => ipcRenderer.invoke('get-pending-mark-data'),
  markRow: (rowData, note, rowIndex) => ipcRenderer.invoke('mark-row', { rowData, note, rowIndex }),
  unmarkRow: (rowIndex) => ipcRenderer.invoke('unmark-row', rowIndex),
  checkRowMarked: (rowIndex) => ipcRenderer.invoke('check-row-marked', rowIndex),
  closeNoteWindow: () => ipcRenderer.invoke('close-note-window'),
  onNoteWindowClosed: (callback) => ipcRenderer.on('note-window-closed', callback),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  endCheck: () => ipcRenderer.invoke('end-check'),
  getLastCheckResult: () => ipcRenderer.invoke('get-last-check-result'),
  closeCheckWindow: () => ipcRenderer.invoke('close-check-window'),
  onNextRow: (callback) => ipcRenderer.on('next-row', callback),
  checkExtensionConnection: () => ipcRenderer.invoke('check-extension-connection'),
  sendToExtension: (message) => ipcRenderer.invoke('send-to-extension', message),
  waitForExtensionMessage: (timeout, expectedType) => ipcRenderer.invoke('wait-for-extension-message', timeout, expectedType),
  openBrowserUrl: (url) => ipcRenderer.invoke('open-browser-url', url),
  openMarksFolder: () => ipcRenderer.invoke('open-marks-folder'),
  openExtensionPage: (browser) => ipcRenderer.invoke('open-extension-page', browser),
  openExtensionFolder: () => ipcRenderer.invoke('open-extension-folder'),
  updateGlobalShortcut: (shortcut) => ipcRenderer.invoke('update-global-shortcut', shortcut),
  getGlobalShortcut: () => ipcRenderer.invoke('get-global-shortcut'),
  openTablePreview: () => ipcRenderer.invoke('open-table-preview'),
  getAllCheckData: () => ipcRenderer.invoke('get-all-check-data'),
  jumpToRow: (rowIndex) => ipcRenderer.invoke('jump-to-row', rowIndex),
  closeTablePreview: () => ipcRenderer.invoke('close-table-preview'),
  onJumpToRow: (callback) => ipcRenderer.on('jump-to-row', callback),
})

